apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: mount
    namespace: kube-mount
spec:
    template:
      metadata:
        labels:
          "mount.kubernetes.io/glusterfs": "true"
          "mount.kubernetes.io/nfs": "true"
          "mount.kubernetes.io/rbd": "true"
          "mount.kubernetes.io/cephfs": "true"
      spec:
        containers:
         - name: mounter
           image: jsafrane/mounter-daemonset:latest
           securityContext:
             privileged: true
           volumeMounts:
             - name: kubelet
               mountPath: /var/lib/kubelet
        volumes:
          - name: kubelet
            hostPath:
              path: /var/lib/kubelet

