apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: mount
    namespace: kube-mount
spec:
    template:
      metadata:
        labels:
          "mount.kubernetes.io/glusterfs": "true"
          "mount.kubernetes.io/nfs": "true"
          "mount.kubernetes.io/rbd": "true"
          "mount.kubernetes.io/cephfs": "true"
          "mount.kubernetes.io/iscsi": "true"
        annotations:
          "volume.alpha.kubernetes.io/propagation": '{"mounter": {"kubelet": "rshared"}}'
      spec:
        hostNetwork: true
        containers:
         - name: mounter
           image: jsafrane/mounter-daemonset:latest
           securityContext:
             privileged: true
           volumeMounts:
             - name: kubelet
               mountPath: /var/lib/kubelet
             - name: sys
               mountPath: /sys
             - name: dev
               mountPath: /dev
             - name: iscsi
               mountPath: /etc/iscsi
             - name: iscsilock
               mountPath: /run/lock/iscsi
             - name: modules
               mountPath: /lib/modules
        volumes:
          - name: kubelet
            hostPath:
              path: /var/lib/kubelet
          - name: sys
            hostPath:
              path: /sys
          - name: dev
            hostPath:
              path: /dev
          - name: iscsi
            hostPath:
              path: /etc/iscsi
          - name: iscsilock
            hostPath:
              path: /run/lock/iscsi
          - name: modules
            hostPath:
              path: /lib/modules
